export const CHAT_LIST_REQUEST = "CHAT_LIST_REQUEST";
export const CHAT_LIST_SUCCESS = "CHAT_LIST_SUCCESS";
export const CHAT_LIST_FAIL = "CHAT_LIST_FAIL";

export const CHAT_CREATE_REQUEST = "CHAT_CREATE_REQUEST";
export const CHAT_CREATE_SUCCESS = "CHAT_CREATE_SUCCESS";
export const CHAT_CREATE_FAIL = "CHAT_CREATE_FAIL";

export const CHAT_DETAILS_REQUEST = "CHAT_DETAILS_REQUEST";
export const CHAT_DETAILS_SUCCESS = "CHAT_DETAILS_SUCCESS";
export const CHAT_DETAILS_FAIL = "CHAT_DETAILS_FAIL";

export const CHAT_SEND_MESSAGE_REQUEST = "CHAT_SEND_MESSAGE_REQUEST";
export const CHAT_SEND_MESSAGE_SUCCESS = "CHAT_SEND_MESSAGE_SUCCESS";
export const CHAT_SEND_MESSAGE_FAIL = "CHAT_SEND_MESSAGE_FAIL";

export const CHAT_DELETE_REQUEST = "CHAT_DELETE_REQUEST";
export const CHAT_DELETE_SUCCESS = "CHAT_DELETE_SUCCESS";
export const CHAT_DELETE_FAIL = "CHAT_DELETE_FAIL";
