export const DOCUMENT_REQUEST = "DOCUMENT_REQUEST";
export const DOCUMENT_SUCCESS = "DOCUMENT_SUCCESS";
export const DOCUMENT_FAILURE = "DOCUMENT_FAILURE";
export const DOCUMENT_UPLOAD_SUCCESS = "DOCUMENT_UPLOAD_SUCCESS";
export const DOCUMENT_DELETE_SUCCESS = "DOCUMENT_DELETE_SUCCESS";
export const DOCUMENT_UPDATE_SUCCESS = "DOCUMENT_UPDATE_SUCCESS";
export const SET_ACTIVE_DOCUMENT = "SET_ACTIVE_DOCUMENT";
export const CLEAR_ACTIVE_DOCUMENT = "CLEAR_ACTIVE_DOCUMENT";
